### ISSUE TITLE
Download grayed out

### ISSUE THREAD

**Issue by amaurynieto** [ninthwalker/saverr#8]
Hiya, have an issue whereby I generate a token, can list the content but when it comes to downloading, the option is grayed out. I've tried dozens of files, all grayed out.

**Comment by amaurynieto** [comment]
<img width="520" alt="Screen Shot 2020-03-30 at 1 20 38 AM" src="https://user-images.githubusercontent.com/32950225/77885701-bb995a00-7224-11ea-9f5d-564796ba69f2.png">

**Comment by ninthwalker** [comment]
I'm not able to reproduce this under normal circumstances.
The download button gets greyed out so as not to allow clicking it multiple times or if no download result is available.

Once you select a result, it should become 'ungrey'.
 then when it starts downloading it will grey out again until the download is finished/cancelled.

Does this only happen on the movies for you, or tv too?
I'm assuming you already tried to close the app, then restart it. It could be possible it thinks a download is still in progress so keeps it greyed out.

You could try a restart of your computer, then a fresh open of the Saverr app and see if it happens right then as well. Let me know. I'll keep this Issue open for a while to see if I can help more.
Thanks!

**Comment by ninthwalker** [comment]
Also, I've added a couple other bug fixes and enhancements in the latest version. If you want to d/l that new script and try it out as well.

**Comment by amaurynieto** [comment]
Thanks so much for following up. Nope, not with the commit from two days ago either. Just tried it. I made a video, also a fresh restart of the computer. let me see if I can post it here (the video)
[Saverr 2020-04-13 02-18-38.lo.mp4.zip](https://github.com/ninthwalker/saverr/files/4468443/Saverr.2020-04-13.02-18-38.lo.mp4.zip)
I had to zip it because it was not uploading the mp4. its 300kb (no sound, just XBOX Game Bar Recording of screen)

**Comment by amaurynieto** [comment]
The capture didnt show the settings (because I didnt set the xbox game bar to capture the entire screen), but i do have a token and its working fine to search and look at the content I have, but downloading is still greyed out.

**Comment by amaurynieto** [comment]
Is there a log somewhere I can send you? i dont really see it even though I have debugging on.

**Comment by amaurynieto** [comment]
04/13/2020 02:18:03: caught exception: System.Management.Automation.MethodInvocationException: Exception calling "DownloadString" with "1" argument(s): "Unable to connect to the remote server" ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond MYIPV4aADDRESS:32400
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at CallSite.Target(Closure , CallSite , Object , String )
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete() at 839. Exception calling "DownloadString" with "1" argument(s): "Unable to connect to the remote server"
04/13/2020 02:19:09: caught exception: System.Net.WebException: The remote server returned an error: (401) Unauthorized.
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord() at 1143. The remote server returned an error: (401) Unauthorized.

**Comment by amaurynieto** [comment]
`04/13/2020 02:18:03: caught exception: System.Management.Automation.MethodInvocationException: Exception calling "DownloadString" with "1" argument(s): "Unable to connect to the remote server" ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond MYIPV4aADDRESS:32400
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at CallSite.Target(Closure , CallSite , Object , String )
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete() at 839. Exception calling "DownloadString" with "1" argument(s): "Unable to connect to the remote server"
04/13/2020 02:19:09: caught exception: System.Net.WebException: The remote server returned an error: (401) Unauthorized.
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord() at 1143. The remote server returned an error: (401) Unauthorized.
`

**Comment by amaurynieto** [comment]
I should add that my IP address is of no import, this is a remote server i have access to that I want to download from (I edited the log where my personal external IP was shown to "MYIPV4aADDRESS"

**Comment by amaurynieto** [comment]
I get a log when I use my personal plex server running on a pi4 - but not when I log on to the remote server im trying to download from (and have access to and can search for titles and stream from Plex on any device)

**Comment by ninthwalker** [comment]
Here's a vid i made as well. 
Shows it working, shows the part of the code that is doing the check there (for movies in this case).
I also show the command to run to test if the logic is working correctly, and if not, the 2 lines to comment out and try again.

Spend a minute running through it, and let me know your results. Thanks!

[saverr_download_Button_issue.zip](https://github.com/ninthwalker/saverr/files/4473079/saverr_download_Button_issue.zip)

**Comment by ninthwalker** [comment]
Oh, also if the Get-Bitstransfer cmd shows nothing, run this below command as well to show me what powershell version you are on. Might help.

`$psversiontable`

**Comment by amaurynieto** [comment]
Hi again. I ran the Get-Bitstransfer command. I got this output.

PS C:\Users\End User\Desktop\saverr-master (2)\saverr-master> Get-BitsTransfer

JobId                                DisplayName                                                                            
-----                                -----------                                                                            
7b8a267d-9279-432c-8fd7-44fa76c6312d C:\Users\ENDUSE~1\AppData\Local\Temp\{B6E833A6-7A2E-49BA-ACE5-F2C0C34EABB9}-gsync64.msi
56485310-e9f0-47ae-84e2-ca0884e032af C:\Users\ENDUSE~1\AppData\Local\Temp\{F9A50441-ADAA-4540-850A-EFAF63A16B70}-80.0.398...

**Comment by amaurynieto** [comment]
`PS C:\Users\End User\Desktop\saverr-master (2)\saverr-master> Get-BitsTransfer

JobId                                DisplayName                                                                            
-----                                -----------                                                                            
7b8a267d-9279-432c-8fd7-44fa76c6312d C:\Users\ENDUSE~1\AppData\Local\Temp\{B6E833A6-7A2E-49BA-ACE5-F2C0C34EABB9}-gsync64.msi
56485310-e9f0-47ae-84e2-ca0884e032af C:\Users\ENDUSE~1\AppData\Local\Temp\{F9A50441-ADAA-4540-850A-EFAF63A16B70}-80.0.398...
`

**Comment by amaurynieto** [comment]
`> $psversiontable



Name                           Value                                                                                                         
----                           -----                                                                                                         
PSVersion                      5.1.18362.628                                                                                                 
PSEdition                      Desktop                                                                                                       
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                       
BuildVersion                   10.0.18362.628                                                                                                
CLRVersion                     4.0.30319.42000                                                                                               
WSManStackVersion              3.0                                                                                                           
PSRemotingProtocolVersion      2.3                                                                                                           
SerializationVersion           1.1.0.1                                                                                                       
`

**Comment by amaurynieto** [comment]
I commented out the if bit, and it worked! Probably have other bittransfers ongoing? of what? I dont use anything that im aware of...
![saverrworks](https://user-images.githubusercontent.com/32950225/79189298-000d2400-7de7-11ea-80e5-5394a8ba962b.png)

**Comment by amaurynieto** [comment]
Another question now that we're here. Is there a way to list out the contents themselves, say the entire list so one can select which content one wants to download and just leave it doing so overnight, you think?

Thanks, great work here.

**Comment by amaurynieto** [comment]
i googled gsync and it seems Google Sync (Google Drive) is getting in the way of Get-Bittransfer. oh well, problem solved by graying out the if bit on

`    # enable download button if no other downloads in progress
    if (!(Get-BitsTransfer)) {
        $button_download.Enabled = $true
    }`

to look like

`    # enable download button if no other downloads in progress
   # if (!(Get-BitsTransfer)) {
        $button_download.Enabled = $true
   # }`

Im guessing I can set multiple download threads now, too.

**Comment by amaurynieto** [comment]
Nope, new issue. download paused because of active Game Mode...something.
![gamemode](https://user-images.githubusercontent.com/32950225/79190197-4794af80-7de9-11ea-8b50-ec8aa2b83149.png)

**Comment by ninthwalker** [comment]
So it looks like there is most likely an old stuck bits-transfer job on your computer causing issues.
Either its old, or it keeps starting up and trying to download. From your get-Bitstransfer command it looks like your nvidia gsync is trying to update but not completing.

Run powershell as admin. Do a get-bitstransfer again to verify it still shows a job.
Then type
`Get-BitsTransfer | Remove-BitsTransfer`
That should remove all jobs. Then open up Saverr again and try.
You can also turn on the debugging option in settings, and close/reopen the app.
That will create a 'saverrLog.txt' file in the same directory as the script. And would show the full error message instead of the truncated one in the GUI.

**Comment by ninthwalker** [comment]
oh, maybe the game mode is this. Try disabling temporarily and see if that helps:

https://www.windowscentral.com/how-enable-disable-game-mode-windows-10

**Comment by amaurynieto** [comment]
Great. Thank you very much!
